name: akalpit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  animations: ^2.0.11
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0
  equatable: ^2.0.5
  swipe_cards: ^0.1.0

  dio: ^5.4.2

  json_annotation: ^4.9.0

  flutter_secure_storage: ^9.0.0
   
  intl: ^0.18.0

  lucide_icons_flutter: ^3.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/akalpit.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
